const facts = [
    "Bananas are berries, but strawberries aren't.",
    "Octopuses have three hearts.",
    "A group of flamingos is called a flamboyance.",
    "Slugs have four noses.",
    "The moon has moonquakes, just like Earth has earthquakes.",
    "Sharks existed before trees.",
    "Cows have best friends and get stressed when they're apart.",
    "A day on Venus is longer than a year on Venus.",
    "Elephants can't jump.",
    "Butterflies taste with their feet.",
    "Humans share about 60% of their DNA with bananas.",
    "A crocodile can't stick its tongue out.",
    "The dot over a lowercase 'i' or 'j' is called a tittle.",
    "Giraffes have no vocal cords.",
    "Wombat poop is cube-shaped.",
    "There are more stars in the universe than grains of sand on Earth.",
    "Koalas have fingerprints almost identical to humans.",
    "Hot water freezes faster than cold water (called the Mpemba effect).",
    "You can't hum while holding your nose.",
    "A bolt of lightning is five times hotter than the surface of the sun.",
    "Spiders can't fly, but some can 'balloon' through the air using silk threads.",
    "An ostrich's eye is bigger than its brain.",
    "The longest hiccuping spree lasted 68 years.",
    "Jellyfish have been around longer than dinosaurs.",
    "Caterpillars completely liquefy in their cocoon before becoming butterflies.",
    "A group of porcupines is called a prickle.",
    "Some turtles can breathe through their butts.",
    "The shortest war in history lasted 38 minutes.",
    "There are more fake flamingos in the world than real ones.",
    "Starfish can regrow their arms—and sometimes even a whole new body.",
    "Ants never sleep.",
    "A cloud can weigh over a million pounds.",
    "The Eiffel Tower can grow taller in the summer because heat makes it expand.",
    "Frogs can freeze solid and still survive.",
    "The longest pizza ever made was over a mile long.",
    "Honey never spoils. Archaeologists have eaten 3,000-year-old honey.",
    "Some snails can sleep for 3 years.",
    "A newborn kangaroo is the size of a jellybean.",
    "An octopus has nine brains—one central brain and one for each arm.",
    "Bats always turn left when exiting a cave.",
    "A blue whale's heart is as big as a small car.",
    "Pineapples take about two years to grow.",
    "The Amazon rainforest produces 20% of the world's oxygen.",
    "Rats and mice laugh when tickled.",
    "You can't fold a piece of paper more than 7 times (try it!).",
    "Seahorses are the only animals in which the males get pregnant.",
    "A group of crows is called a murder.",
    "Rain contains vitamin B12.",
    "The first oranges weren't orange—they were green.",
    "Giant pandas can poop up to 40 times a day.",
    "The inventor of the Frisbee was turned into a Frisbee after he died.",
    "A single strand of spaghetti is called a spaghetto.",
    "Tigers have striped skin, not just striped fur.",
    "Tomatoes were once thought to be poisonous.",
    "A bolt of lightning can reach temperatures of 30,000 Kelvin.",
    "Bees sometimes sleep in flowers.",
    "Sloths can hold their breath longer than dolphins.",
    "Bubble wrap was originally intended to be wallpaper.",
    "Reindeer eyes turn blue in winter to help them see in the dark.",
    "Earthworms have five hearts.",
    "The heart of a shrimp is located in its head.",
    "A group of owls is called a parliament.",
    "Some lizards can squirt blood from their eyes to scare off predators.",
    "Peanuts are not nuts—they're legumes.",
    "Rainbows can appear at night. They're called moonbows.",
    "Penguins propose to their mates with a pebble.",
    "Humans are the only animals with chins.",
    "There's a species of jellyfish that can live forever.",
    "Tardigrades (water bears) can survive in space.",
    "Apples float because 25% of their volume is air.",
    "Pigeons can do math and recognize themselves in a mirror.",
    "A narwhal's tusk is actually a tooth.",
    "Dogs' noses are as unique as human fingerprints.",
    "Some fish cough to clear their gills.",
    "The smell of freshly-cut grass is actually a plant distress signal.",
    "There's a planet where it rains molten glass sideways (HD 189733b).",
    "Your stomach gets a new lining every few days.",
    "Snakes can sense heat with their faces.",
    "Mosquitoes are attracted to people who just ate bananas.",
    "Sharks are older than Saturn's rings.",
    "You can hear a blue whale's heartbeat from 2 miles away.",
    "Octopuses can change color in less than a second.",
    "Some frogs can be frozen solid and come back to life.",
    "Cows have almost 360-degree vision.",
    "The longest-living animal is the ocean quahog clam (over 500 years old).",
    "An eagle can spot a rabbit from 3 miles away.",
    "Bamboo can grow over 35 inches in a day.",
    "Some ants explode to protect their colony.",
    "Chickens can remember over 100 faces.",
    "There's a jellyfish that can clone itself.",
    "Male seahorses give birth, not the females.",
    "The human nose can detect over 1 trillion scents.",
    "A group of frogs is called an army.",
    "Caterpillars have 12 eyes.",
    "Snails have 14,000 teeth.",
    "Wolves communicate by using facial expressions.",
    "Rabbits can see behind them without turning their heads.",
    "Some parrots can live over 80 years.",
    "A hippo's sweat is pink.",
    "Lobsters taste with their legs.",
    "Bats are the only mammals that can fly.",
    "A single honeybee makes about 1/12th of a teaspoon of honey in its life.",
    "Turtles live on every continent except Antarctica.",
    "Flies have taste buds on their feet.",
    "Some animals glow in the dark—this is called bioluminescence.",
    "Sharks don't have bones—only cartilage.",
    "A day on Uranus lasts about 17 hours.",
    "Some cats are allergic to humans.",
    "A group of zebras is called a dazzle.",
    "The longest recorded flight of a chicken is 13 seconds.",
    "Your bones are about five times stronger than steel of the same density.",
    "Some sea cucumbers can eject their organs to scare predators.",
    "There's a mushroom that glows in the dark.",
    "Ravens can mimic human speech like parrots.",
    "Male peacocks use their colorful tails to impress females.",
    "Antarctica is the driest, windiest, and coldest continent.",
    "Fireflies produce light through a process called bioluminescence.",
    "Snakes smell with their tongues.",
    "Crickets hear using ears on their legs.",
    "The fingerprints of a koala are almost indistinguishable from a human's—even under a microscope.",
    "Sharks can go into a trance when flipped upside down.",
    "Goats have rectangular pupils.",
    "There's a plant that eats bugs—it's called a Venus flytrap.",
    "Some spiders can fly using silk parachutes.",
    "A group of kittens is called a kindle.",
    "Each king in a deck of playing cards represents a real king in history.",
    "The human body glows in the dark—but the light is too weak to see.",
    "Octopuses can taste through their arms.",
    "Cows can walk up stairs but not down them easily.",
    "Some fish can walk on land—like the mudskipper.",
    "A rainbow can only appear in the sky opposite the sun.",
    "The first computer mouse was made of wood.",
    "Saturn could float in water because it's so light.",
    "Snowflakes can have up to 200 sides.",
    "Pine cones can close up when it's cold and open when it's warm.",
    "Some ants farm fungi for food.",
    "You can't burp in space (without gravity to separate liquids and gases).",
    "One teaspoon of honey represents the life's work of 12 bees.",
    "There's a species of ant that can explode itself like a balloon.",
    "The human stomach gets a new lining every 3–4 days to protect itself from its own acid.",
    "There are pink dolphins in the Amazon River.",
    "Beavers have transparent eyelids so they can see underwater.",
    "A flea can jump 200 times its body length.",
    "Toucans regulate their body temperature using their beaks.",
    "Most lipsticks contain fish scales to make them shiny.",
    "The human brain uses about 20% of the body's total energy.",
    "Owls can turn their heads up to 270 degrees.",
    "The world's oldest toy is a stick (really—it was added to the Toy Hall of Fame).",
    "Camels have three eyelids to protect their eyes from sand.",
    "Bananas grow upside down, pointing toward the sun.",
    "Some frogs don't have lungs—they breathe through their skin.",
    "The heaviest onion ever grown weighed over 10 pounds.",
    "Kangaroos can't walk backwards.",
    "The average cumulus cloud weighs over 1 million pounds.",
    "The fastest recorded sneeze was over 100 miles per hour."
];

function showRandomFact() {
    const randomIndex = Math.floor(Math.random() * facts.length);
    const factDisplay = document.getElementById("factDisplay");
    factDisplay.textContent = facts[randomIndex];
}
